### ISSUE TITLE
Documentation of data ingestion scripts

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-api#574] opened 2020-01-10 14:38 UTC
As a first step toward #439 and as a generally useful document, it would be good to clearly document, for each of the data ingestion scripts:

 - Source(s) the script is pulling data from
 - What data is being ingested
 - Where in the GO database data is being saved to

As a bonus, a bit of documentation about assumptions the script makes, if any, and notes on how the data is used on the frontend.

The data ingestion scripts are all here: https://github.com/IFRCGo/go-api/tree/master/api/management/commands (@szabozoltan69 let me know if there are any scripts importing data into GO that are not covered in that folder?)

@LukeCaley Let me know if this documentation already exists anywhere?

@szabozoltan69 will probably ask for some help as I go through the scripts.

cc @nanometrenat

**Comment by szabozoltan69** [comment] 2020-01-10 14:44
Thanks for all these, @batpad - as far as I know there is no other (repetitive) data scraper, that is in api/management/commands, because all the crontab rows points there. (Even the new pdf scraper will have a handle there.)
Unfortunately there is some kind of data ingestion on frontend side also (fdrs?), it should be discovered also.

**Comment by szabozoltan69** [comment] 2020-01-13 11:03
Though there is no ingestion scripts for the "countries", we could make a repeated job, to check if the countries on backend and frontend side are well paired. (A better solution would be a single source for these data, but I suppose it would be difficult.) This "country mismatch" was the root cause of this also: https://github.com/IFRCGo/go-frontend/issues/936

**Comment by szabozoltan69** [comment] 2020-01-30 12:45
**A brief documentation of ingest scripts and the written tables**

api/management/commands/ingest_appeal_docs.py
  appeal documents ingest from
  www.ifrc.org/en/publications-and-reports/appeals - puts them to 
  AppealDocument table

api/management/commands/scrape_pdfs.py
  different pdf-s ingest from 
  www.ifrc.org/Utils/Search/Rss.ashx - puts them to 
  Emergency Operations Datasets 	
  Emergency Operations Emergency Appeals 	
  Emergency Operations Final Reports 	
  Emergency Operations People Reached tables (epoa, ou, fr, ea)

api/management/commands/ingest_appeals.py
  appeals ingest from
  go-api.ifrc.org/api/appealbilaterals - puts them to
  Appeal table

api/management/commands/ingest_gdacs.py
  gdacs events ingest from
  www.gdacs.org/xml/rss_7d.xml - puts them to
  Event ( = Emergency) table, with source name "GDACs scraper"

api/management/commands/ingest_who.py
  WHO events ingest (if will be run) from
  www.who.int/feeds/entity/csr/don/en/rss.xml and
  www.who.int/feeds/entity/hac/en/rss.xml - puts them to 
  Event ( = Emergency) table, with source name "WHO scraper"

api/management/commands/index_and_notify.py
  if new appeal, event or field report appears, this script
  updates the ElasticSearch index and
  send notification if needed (to the subscribers).
  Also sends notifications for followed events and ingest issues.

api/templates/admin/base_site.html
  contains a possibility for displaying /!\ sign in case of ingest issue.
  the related HAVING_INGEST_ISSUE variable was set to False in 
  main/context_processors.py

databank/management/commands/sources/WB.py
  reads data from
  api.worldbank.org/v2/country/ALL/indicator/SP.POP.TOTL

databank/management/commands/sources/INFORM.py
  reads data from 
  drmkc.jrc.ec.europa.eu/inform-index/API/InformAPI/Countries/Scores
  and writes via databank/management/commands/ingest_databank.py

databank/management/commands/sources/RELIEFWEB.py
  reads data from
  api.reliefweb.int/v1/disasters
  and writes via databank/management/commands/ingest_databank.py

databank/management/commands/sources/FDRS.py
  reads data from
  data-api.ifrc.org/api/entities/ns and
  data-api.ifrc.org/api/Data
  and writes via databank/management/commands/ingest_databank.py
        
databank/management/commands/sources/START_NETWORK.py
  reads data from
  startnetwork.org/api/v1/start-fund-all-alerts
  and writes via databank/management/commands/ingest_databank.py

databank/management/commands/sources/FTS_HPC.py
  reads data from
  api.hpc.tools/v1/public/fts/flow?countryISO3={0}&groupby=year&report=3 and
  api.hpc.tools/v1/public/emergency/country/{0}
  and writes via databank/management/commands/ingest_databank.py
  
databank/management/commands/ingest_databank.py
  reads data from the above CAPITAL sources and writes data to
  CountryOverview

notifications/notification.py
  uses smtp server, needs ifrc password.
  In case of failure: notification alert like the other "ingest issues"

**Comment by nanometrenat** [comment] 2020-03-06 14:01
Some time back I copied the above info into our Teams space wiki (thanks Zoltan!)

@batpad there were several other comments in this ticket - re monitoring etc. - and also there is more work we can do on the teams wiki doco to pad out the info provided above.  So, keeping this ticket open unless you are keen to close.

Thanks

**Comment by LukeCaley** [comment] 2020-03-19 08:10
@GregoryHorvath any further action on documenting this process required or can we close this ticket?

**Comment by GregoryHorvath** [comment] 2020-03-19 09:54
@LukeCaley Other than @szabozoltan69's input I don't have anything to add on this. I'll update the SMTP part though when the new API for the sending of emails will be tested and used.

**Comment by LukeCaley** [comment] 2020-03-24 21:09
Thanks for the work and testing on this @GregoryHorvath.  Email API tested and about to be merged to production.

**Closed by LukeCaley** 2020-03-24 21:09 UTC
Labels: documentation
