### ISSUE TITLE
Provide a Rich Text Editor option for snippets

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-api#670] opened 2020-04-18 23:37 UTC
## Issue
Further to the below, and other conversations, we need to add a Rich Text Editor for Snippets 

- https://github.com/IFRCGo/go-frontend/issues/1011 
- https://github.com/IFRCGo/go-frontend/issues/931
- https://github.com/IFRCGo/go-api/issues/667

Particular driver right now is on Emergency pages, but Country and Regional pages also have snippets and it could be useful there too.

The Emergency Page snippets have

- a text box (not Rich Text) where users can paste in EITHER an iframe/URL link to embed e.g. a dashboard (this is the main use case and is critical to keep being supported) OR users can paste in html (this is the use case we're trying to help here - e.g. the Technical Guidance section of COVID-19 is html from another source copied and pasted in)
- an option to select an image for display (also need to keep this option)
- other options for visibility/position/tab/delete (these options also need to stay

What we'd like to have is a way for users to write Rich Text content (including ability to hyperlink to other sites, or to link to documents on GO) within the snippet so they don't have to create html elsewhere to paste in.

Hope this helps explain things but shout if further info required.

**Comment by GregoryHorvath** [comment] 2020-06-02 08:44
Just copying @teklal 's comment here from a duplicate of this and closing that issue: https://github.com/IFRCGo/go-api/issues/667#issuecomment-617654396

> - Surge alerts, the "Message" field https://prddsgocdnapi.azureedge.net/notifications/surgealert/add/ here the messages that are shared already most of the time have bulleted lists but they don't show on the frontend in the desired way
> - in field reports people sometimes add links to the "source" field so it would be good to be able to support the sharing of links there and having them properly show as links on the frontend too
> - snippets #670
>
> I'll add more when I think of other places.

**Comment by GregoryHorvath** [comment] 2020-06-02 08:46
@nanometrenat @teklal  Country, Region and Emergency Snippets are now RTE fields, deployed to staging.

**Comment by nanometrenat** [comment] 2020-06-04 12:51
Thanks @GregoryHorvath Unfortunately now I can't just copy and paste an iframe link into the snippet and have it display - if I just copy and paste directly then it shows as normal paragraph rather than as an iframe.  As per the description above iframes are our base use case for snippets.

In order to get an iframe to display I need to go into "Tools"/"Source code" and paste it there...
@teklal @LukeCaley and team, in terms of usability what do you think about the extra steps for iframe?  Might be simpler for the user to have to actively choose if they want rich text for snippets or just to copy in code?  Or alternatively perhaps we could put explanatory text to help the users?

**Comment by teklal** [comment] 2020-06-04 13:22
That's a good point @nanometrenat and I was thinking about the exact same myself the other day when testing this. 

I think an explanatory text may be a good way to go. In the end, the number of users that have been embedding the iframes is not _that_ big (often it's the same people doing it for different emergencies) and these people would be tech-savvy enough to figure out the extra steps (especially with a help text). I think having to actively choose between RTE or code may be more confusing? I do agree though that as iframes have so far been the main way to use snippets it's a bit cumbersome having to go through those extra steps when previously one could just copy paste directly. I wonder if with the new tabs feature and RTE we'll see snippets being used in more different ways?

Luckily it seems the already embedded iframes automatically work and do not need to be reconfigured.

**Comment by nanometrenat** [comment] 2020-06-04 13:28
NOTE ALSO - we need to consider migration - what happens on the first edit after the new functionality is in place.  For my test page, as soon as I edited anything then the system automatically added p tags to all the existing snippets (whether iframes or not), and the existing snippet that was just text but with an html a href hyperlink was automatically turned into text with no hyperlink.  So we would need to make a plan re migration checks (and potential data updates) when this is implemented, to make sure that editing something _else on an emergency page doesn't break existing snippets...

https://dsgocdnapi.azureedge.net/api/event/3833/history/

**Comment by nanometrenat** [comment] 2020-06-04 13:37
Also noting that the css doesn't seem to be being applied to the snippets - as you can see, my double-indented bullets etc. look fine in back end but not in front end:
https://dsgoproxyapp.azurewebsites.net/emergencies/3833#additional-information
Same thing as https://github.com/IFRCGo/go-frontend/issues/1011#issuecomment-607177598

**Comment by GregoryHorvath** [comment] 2020-06-19 11:19
Latest changes are on staging:
- Added the Embed media button to a toolbar for RTEs on the backend, which should be used for adding `<iframe>`s
- Removed the automatic `<p>` tag which was added by RTE fields by default on the backend, and added it on the frontend

Checked changing the fields' type back-and-forth, didn't find any current content which would be affected by the change, except the `<p>` tags which shouldn't happen by the latest changes, though I checked manually.

cc @teklal @karitotp

**Comment by karitotp** [comment] 2020-06-19 21:58
I was testing this by paste html code from the other emergency pages, but I did not get the same result in frontend, it is displayed just as code, even though the text is the same in admin.
![Screenshot from 2020-06-19 16-53-13](https://user-images.githubusercontent.com/11504548/85182159-77c75700-b24d-11ea-9007-e53e7dbdb45f.png)

It is possible that I am not testing correctly, because the edit tools work good. @teklal, could you please give me some inputs to do the test here.

**Comment by GregoryHorvath** [comment] 2020-06-22 08:08
@karitotp Did you use the Insert > Media > Embed function (or from the toolbar)?
![image](https://user-images.githubusercontent.com/30079559/85263824-0a474080-b470-11ea-95c5-aa04680ca997.png)

It seems to be you've either used a code-block and/or a plain paste text paste into the field on the backend maybe? Those won't work, sorry I didn't specify this part.

**Comment by nanometrenat** [comment] 2020-06-25 16:26
Thanks @GregoryHorvath @karitotp for doing pedantic testing, that's fab.

My question would be, is the above behaviour _only_ for iframes that were already there before the change?  Or would it also happen for new iframes that are saved after the change, and then would have line breaks added the next time the emergency is saved?  If it's a one off migration thing I wouldn't be massively worried but if it's a thing that happens every time we should definitely fix.

@LukeCaley in the user comms when this gets released it needs to be made clear what the new instructions are - as per Greg's screenshot at https://github.com/IFRCGo/go-api/issues/670#issuecomment-647358030

THAAAANKS!

**Comment by GregoryHorvath** [comment] 2020-06-26 08:21
@nanometrenat Good question, just tested it and it happens to new ones too if they only have `<iframe>`s in them, count doesn't matter either. But if there is at least one other character in the Snippet or anything this doesn't happen.

**Comment by nanometrenat** [comment] 2020-08-11 14:41
@GregoryHorvath @batpad I can see this is in Staging - so should it be in Ready for QA now?  If not then will put to backlog.

**Comment by batpad** [comment] 2020-08-11 15:13
I believe it is pending this fix to fix a character encoding error to be re-tested: https://github.com/IFRCGo/go-api/pull/847 - @GregoryHorvath that PR should be good to merge, apologies for the late review, and then we can move this ticket as well as the fix for character encoding back to Ready for QA?

**Comment by GregoryHorvath** [comment] 2020-08-12 09:11
@batpad @nanometrenat Yep this is in staging again, but yes there is another PR with the special characters' saving fix which I can get into staging soon alongside other stuff. I'll make sure to comment here if they are on staging and move the ticket to RfQA.

**Comment by LukeCaley** [comment] 2020-09-01 07:23
@GregoryHorvath could you update on the status of this ticket?  As there has been some back and forth above it would be great if you could list the features to be tested on staging here for @karitotp

**Comment by GregoryHorvath** [comment] 2020-09-01 07:47
xref: https://github.com/IFRCGo/go-api/issues/837#issuecomment-683780658
cc @LukeCaley

**Comment by GregoryHorvath** [comment] 2020-09-07 09:38
Foundings so far:
1. Need configuration to be set to `'entity_encoding': 'raw'` for multilingual support
2. With this setting my tests went:
  2.1 pasting plain text with HTML tags in it
  `<h1>Text h1</h1>` saved as `&lt;h1&gt;Text h1&lt;/h1&gt;` into the database and shown up like plain text on the frontend: 
![image](https://user-images.githubusercontent.com/30079559/92372236-ee614b80-f0fc-11ea-8b2a-e00772dc4281.png)
  2.2. clicking the 'Insert/edit media' and pasting into the 'Embed' section
  `<h1>Source code h1</h1>` saved as `<h1>Source code h1</h1>` into the database an shown up right on the frontend: 
![image](https://user-images.githubusercontent.com/30079559/92372843-ce7e5780-f0fd-11ea-8396-174e1ee357b8.png)
  2.3 tested with an `<iframe>` demo-map containing multiple properties, pasting it to the 'Embed' section as well and it showed up right

This now seems like a pretty normal behaviour for a RTE, but you should take the call on it. But this would still mean that if anyone would input "HTML characters" (like `<>/` etc) into the plain textbox, the CSV exports would get those funky strings. Most probably we need to fix those at the CSV export front.
@LukeCaley 
cc @batpad

**Comment by nanometrenat** [comment] 2020-09-10 06:29
> This now seems like a pretty normal behaviour for a RTE, but you should take the call on it. But this would still mean that if anyone would input "HTML characters" (like `<>/` etc) into the plain textbox, the CSV exports would get those funky strings. 

Thanks @GregoryHorvath think this is a communication/training thing - @LukeCaley when this is released (with translations) very clear instructions need to be communicated to back-end admin users showing them how to use the new fab RTE functionality.  Just went through it with @anamariaescobar today also.

**Comment by GregoryHorvath** [comment] 2020-09-16 11:31
@LukeCaley Someone should (re)test this to see if it should go into this release or not.

**Comment by tovari** [comment] 2020-09-17 14:01
We can insert html codes by using the Source code button:
![image](https://user-images.githubusercontent.com/68283148/93481047-6cdc9b00-f8fe-11ea-9a49-eea80547c3d6.png)
The exported csv will still contain the HTML characters, but I consider this a feature as the formatting of the text (as an html code) is also preserved in the export.
@LukeCaley, I think this could go to release.

**Comment by tovari** [comment] 2020-09-21 14:28
The rich text editor for snippets works fine.
We need a further discussion, if the html code parts should be or shouldn't be filtered in the CSV export.

**Closed** 2020-09-23 11:53 UTC
Labels: backlog
