### ISSUE TITLE
36. Update Emergency when Field Report updates

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-api#496] opened 2019-07-25 09:54 UTC
The broad issue:

When we create a Field Report that does not have an Emergency associated, we create an Emergency. But, when a user updates details on the Field Report we do not update the Emergency.

This is especially a problem when a user edits Districts on the Field Report - these do not now update the Districts on the map on the Emergency page.

We need to think through how to best handle it, and give users a good way to update the regions / districts.

Creating this issue without a definitive solution, but to remind us to think about it and implement something.

cc @LukeCaley @mmusori @guipizzini

**Comment by szabozoltan69** [comment] 2019-07-25 10:00
Just a comment: Sometimes data redundancy makes sense, if we want override (but keep) old data. (This issue has some common points with https://github.com/IFRCGo/go-api/issues/464 )

**Comment by nanometrenat** [comment] 2020-01-17 10:56
Below details added following business rule discussions with @LukeCaley @mmusori @teklal today.
Historically the official business process was to submit only one field report (which was sometimes subsequently edited) however in reality multiple field reports should be able to be submitted, to show changes in the situation over time.

Current behaviour:  When a Field Report is edited or a new Field Report is created, the information in the Emergency page is not updated.

Desired behaviour:  New field reports (or updates to existing field reports) will update the emergency page (including the map regions) and override any manually-input emergency information that is older.  It should be possible to have multiple field reports against an emergency so that users can see the history of how the situation evolved.
NB - If a field report was created separately (e.g. if the user did not select an emergency when creating their field report so a new emergency was created), when the field report is moved over it should also update the emergency.

Doing this will also mean that Early Warning Field reports would be better supported.  @mmusori  will also bear this in mind during discussions around Informal Updates.

@batpad we will need to have a chat re complexities and considerations

**Comment by nanometrenat** [comment] 2020-01-17 14:59
Also xref https://github.com/IFRCGo/go-api/issues/464 re database structure for 'event' records

**Comment by batpad** [comment] 2020-01-24 11:05
My broad suggestion here would be:

 - Continue to create an emergency when a new field report is created not tied to an existing emergency
 - Do not copy over any values from the field report into the emergency
 - Calculate the various values for the emergency "at query time", aggregating values from the various field reports tied to the emergency, as needed.

We should talk about details of what values should be computed from the values in the field report, and how that aggregation needs to happen. It does seem cleaner to me if we avoid "copying over" values in the database as much as possible. It would be great to switch over how we get various values for an emergency based on field reports and potentially manually input entries.

@nanometrenat will be great to spec the details here a bit - am pretty sure what I described reflects the expectations of user behaviour here - we'd just need clarity on how values for the emergency are to be displayed / aggregated from the field reports attached to it (take `x` value from "latest" field report, for eg.).

**Comment by batpad** [comment] 2020-01-24 11:13
Just dropping a reference to the code that's handling creating the Emergency if the field report isn't associated with an existing emergency: https://github.com/IFRCGo/go-api/blob/master/api/drf_views.py#L568

**Comment by nanometrenat** [comment] 2020-03-05 17:38
https://github.com/IFRCGo/go-frontend/issues/796 was about emergency page redesign and may relate.

More recent field report tickets under https://github.com/IFRCGo/go-frontend/issues/984 and https://github.com/IFRCGo/go-frontend/issues/985

Today in test and Prod when trying to create a second Field Report (in front end) for an existing emergency the existing emergency was not appearing in the dropdown (possibly filtered out due to already having a field report??)  More testing required around the Elastic Search here.  But I can't find doco re v1 of the API (ES specifically)...

Putting doco of current behaviour from today's testing into Teams for reference.

**Comment by nanometrenat** [comment] 2020-03-06 18:09
OK think there's a bigger problem with the search function - it may not be deliberately excluding emergencies with no field report.  Logged https://github.com/IFRCGo/go-frontend/issues/989 for investigation

**Comment by batpad** [comment] 2020-04-09 11:25
@LukeCaley this is the ticket relating to keeping data consistent between emergencies and field reports. This will need more detailed speccing in terms of what logic exactly should be implemented for the relationship between the data on the field reports, and how they get aggregated to the emergency.

**Comment by nanometrenat** [comment] 2020-04-21 08:39
As at today, in conjunction with @mmusori @teklal @LukeCaley we confirmed that
* situation overview and numeric figures from latest attached field report will show on the emergency page by default
* if you click "hide attached field reports" on the emergency then the numeric figs from the FR will not show, but the situation overview from the latest FR *will* show
* if you update the Summary in the emergency then that will show on the emergency page (instead of the situation overview from the latest field report) but figs from FR will still show unless hidden.

Closing this ticket and @mmusori will log new tickets if further changes are required.

**Closed by nanometrenat** 2020-04-21 08:39 UTC
