### ISSUE TITLE
[PROD] cronjob log not notifying when go-api.ifrc.org breaks

### ISSUE THREAD

**Issue by nanometrenat** [IFRCGo/go-api#750] opened 2020-05-28 14:26 UTC
## Issue
As per SRV-22386 there are errors when calling GO-API to get Appeals data

However the build from https://github.com/IFRCGo/go-api/issues/439 should mean that these are reported and notified rather than ignored.

Greg to please take a look and make sure the errors are better handled.

2020-05-28 13:45:39 ERROR    Error querying Appeals API
[2020-05-28 13:45:39,850] ingest_appeals: ERROR - Error querying Appeals API

**Comment by nanometrenat** [comment] 2020-06-15 11:12
FYI we got good notifications over the weekend when go-api.ifrc.org was returning a not-useful response (Unable to retrieve appeals from the database.)

**Comment by GregoryHorvath** [comment] 2020-09-03 14:34
The above PR helps with the logging most of the possible errors. Do we want sending an email to the IM Team when the ingestion fails?
(usually if it fails it's because the Appeals API returns 500, although the `ingest_appeals.log` is the most clean out of all, couldn't find any errors in it since we retain those logs)

**Comment by nanometrenat** [comment] 2020-09-03 14:38
Yes please to notifications by email
cc @tovari  FYI

Thanks!

**Comment by GregoryHorvath** [comment] 2020-09-04 12:41
@nanometrenat thanks for the concern, gladly the refactor was needed because of (and touch) only the error handling parts, and the rest is more like simplifying parts of the code to help maintainability rather than changing any business logic. The only thing I changed for the logic is that previously newly added Appeals then were also counted for the "modified" Appeals, so I excluded them from there to remove the double work, and they were also counted towards the modified records count.

As I've figured Zoltan's already existing code should pick up the newly added Cron error logs and send notifications about those to the IM email address. But with the most recent PR I added (3) retries to both the Appeals and Bilaterals API requests in case they somehow fail at first, and only after that it will return with an error so hopefully this will help with getting less 500 errors (unless there's something really wrong with those APIs).

**Comment by GregoryHorvath** [comment] 2020-09-07 11:51
The changes were deployed to staging 2-3 days ago, the log files don't show any error.

**Comment by nanometrenat** [comment] 2020-09-11 07:23
Hi @GregoryHorvath thanks but I think there's still a gremlin.  In Staging, the ingest_appeals has been Warned then immediately Successful every single time it has run in Staging over the last few days.  Whereas in Production (which calls the same endpoint) it has been successful 100% of the time (i.e. I don't think there are problems at the go-api end).

Can you please take another look and see what's up?

Thanks!

![image](https://user-images.githubusercontent.com/33625192/92882740-7e123d00-f410-11ea-967f-521b022dd9ab.png)

**Comment by GregoryHorvath** [comment] 2020-09-11 07:28
@nanometrenat Thanks for catching this. It's weird because I couldn't find any of these in the logfiles. I'll try to reproduce it locally.

**Comment by GregoryHorvath** [comment] 2020-09-11 12:40
> Hi @GregoryHorvath thanks but I think there's still a gremlin. In Staging, the ingest_appeals has been Warned then immediately Successful every single time it has run in Staging over the last few days. Whereas in Production (which calls the same endpoint) it has been successful 100% of the time (i.e. I don't think there are problems at the go-api end).

Deployed the fix for this to staging, it shouldn't show up from now if there are no errors.

**Comment by szabozoltan69** [comment] 2024-01-22 12:51
Thanks @nanometrenat for this found! :-)

**Closed by szabozoltan69** 2024-01-22 12:51 UTC
