### ISSUE TITLE
Create an endpoint for all the ENUM fields

### ISSUE THREAD

**Issue by frozenhelium** [IFRCGo/go-api#889] opened 2020-09-10 11:45 UTC
As we have the values of the ENUM constant fields separately maintained in the frontend and backend, which is not a good practice. So to keep only one source of truth, all those constants should be loaded from the API.

CC: @batpad @geohacker @GregoryHorvath @thenav56

**Comment by szabozoltan69** [comment] 2023-02-16 17:03
Duplicate of https://github.com/IFRCGo/go-api/issues/1552

**Closed by szabozoltan69** 2023-02-16 17:03 UTC
Labels: enhancement, help wanted, Maintenance, refactor
