### ISSUE TITLE
Inconsistency in a user's "last login" and "date joined" times

### ISSUE THREAD

**Issue by teklal** [IFRCGo/go-api#522] opened 2019-10-07 12:44 UTC
On the backend page for a user, I have encountered a few cases where the "date joined" time is more recent than the "last login" date. What could be the reason for this (as it logically does not make sense)?

Below a few examples of this.

![image](https://user-images.githubusercontent.com/52411237/66312620-50c03380-e911-11e9-8953-4907ce88b68d.png)

![image](https://user-images.githubusercontent.com/52411237/66312898-b8767e80-e911-11e9-93f6-00bc760da90c.png)

**Comment by teklal** [comment] 2019-10-07 13:06
Related to this issue:

There is a field report submitted by a user on June 21, 2019, 5:50 p.m.

![image](https://user-images.githubusercontent.com/52411237/66313230-510cfe80-e912-11e9-87e6-a6e8695db84d.png)

![image](https://user-images.githubusercontent.com/52411237/66313187-3b97d480-e912-11e9-9a2f-0f60b069803a.png)

But based on the information in the backend that user would not have logged in after January . 

![image](https://user-images.githubusercontent.com/52411237/66313335-80bc0680-e912-11e9-8b9e-81949c215fb8.png)

**Comment by szabozoltan69** [comment] 2020-01-17 09:50
I'll check it...

**Comment by szabozoltan69** [comment] 2020-01-17 15:19
A strange thing is:
There are 4285 records in user table, and in 2541 cases date_joined>last_login.
I suppose that there were some kind of "scripted" batch update, because in most part of this cases has 2018-02-22 as date_joined. (Maybe this data was null and for some statistics it was filled up?)

The latest example of this "later joined than last login" has 2019-04-01 date_joined, so probably this is not a still-existing problem, because since then there are 882 users joined. But still investigating the root cause...

**Comment by szabozoltan69** [comment] 2020-01-17 15:34
To have "more accurate statistics" I can run an update for these inconsistent cases: let's update these date_joined values for the last_login date (or a day before it). Shall I?

**Comment by nanometrenat** [comment] 2020-01-17 16:50
Thanks for investigating @szabozoltan69 it makes sense if most of the users affected have the same date_joined - that must've been when users were migrated from the old DMIS system - so in that 2018-02-22 date is correctly reflecting reality.  We don't need to update just for cosmetic reasons, but thanks for the suggestion.

What does need more investigation though is the case Tekla found where a user's last login date is many months before the date they carried out an action on the platform.  There are several possible explanations though - e.g. if something was updated via API, potentially if they didn't type their password but had kept an active session, ??? maybe other options.  But we need to figure out how this scenario can occur so we can make sure the user actions are being well logged.

Thanks as always!!

**Comment by szabozoltan69** [comment] 2020-01-17 18:21
Thank you @nanometrenat – I continue the investigation and keep my eyes open. :-)

Otherwise not only for cosmetic reason can be good an update for these "migration join dates", but the first login is a better approximation for the join date, than the wired-in 2018.02.22, and if someone would like to have some statistics, then it would be closer to the truth. But I understand if no database manipulation is wished now.

Thankfullllly! :)

**Comment by nanometrenat** [comment] 2020-01-30 13:47
Having tested this, the Last login date is only populated when a user logs into the Admin site.  It is not populated or updated when a user logs into the Front End.

**Comment by nanometrenat** [comment] 2020-06-04 19:54
@teklal hope you don't mind us closing this based on the fact that 956 is the ticket specific to front end date logging - and I think we are happy to leave the weird dates now we know the explanation... cheers

**Closed by nanometrenat** 2020-06-04 19:54 UTC
Labels: maintenance
