### ISSUE TITLE
Add comprehensive test coverage for all API end-points

### ISSUE THREAD

**Issue by batpad** [IFRCGo/go-api#797] opened 2020-07-01 05:35 UTC
**Is your feature request related to a problem? Please describe.**

As our API gets increased usage, it would be great to overhaul our approach to testing and work toward 100% test coverage of the API end-points. So far, we've got some tests to cover tricky bits of logic and aggregation, here being a nice example: https://github.com/IFRCGo/go-api/blob/develop/deployments/test_views.py

The patterns and organization for tests we use currently worked fine for the ad-hoc approach we've had so far for testing, allowing us to quickly write tests for tricky bits or for identified regressions. But it does not lend itself well to easily adding new tests for new features and end-points, or updating tests for changes, or coherently measuring test coverage. Changing the structure to allow for better code organization and developer friendliness, and having clear developer guidelines on adding and updating tests would go a long way toward this goal.

**Describe the solution you'd like**

I'd propose an overhaul of our API testing approach, and spending some time bringing consistency to how we write API tests. Below is a bit of a brain-dump of ideas, of roughly an approach I think makes sense, very happy to have more thoughts and suggestions here:

 - First, create a separate `tests` folder inside each app instead of the `test_views.py` single file. Within that, have a separate test file for each entity / API end-point being tested.

 - Create "factories" for each type of entity to easily populate the test database with fake data. This can be a bit of work to initially setup, but would then easily let us add many items to the test db and easily test all filters, etc. We would likely use something like `factory_boy` and `faker` or similar: https://medium.com/analytics-vidhya/factoryboy-usage-cd0398fd11d2

 - I'd love to use something like a "snapshot testing" approach, where our tests essentially:
   - Load test db with test data
   - Call each API end-point, with combinations of filters, limits, formats, etc.
   - Check each response against a "snapshot".
   - Have a good workflow to create initial snapshots, inspect when snapshots change, and update snapshots.

I have used Snapshot testing a fair bit in Javascript-land, but never with python / django. I found this package which seems to be the approach I'm advocating for: https://github.com/syrusakbary/snapshottest - I'd be surprised if there wasn't a recommended, consistent way to do this with Django + DRF, I'll do a bit more looking around.

@thenav56 would love to hear your thoughts and suggestions here.

@gulfaraz checking if this might be something you're able to take up - if you have the bandwidth and we can work together to setup the consistent structure and document test-writing, we can then split up work among all of us to cover all entities.

cc @GregoryHorvath @nanometrenat @LukeCaley

**Comment by szabozoltan69** [comment] 2023-02-16 16:58
Duplicate of https://github.com/IFRCGo/go-api/issues/812

**Closed by szabozoltan69** 2023-02-16 16:58 UTC
