### ISSUE TITLE
Add branch offices data to the API - Local unit mapping

### ISSUE THREAD

**Issue by geohacker** [IFRCGo/go-api#1535] opened 2022-09-22 04:15 UTC
This will involve:
* [ ] Inspecting the data @jhenshall @geohacker 
* [ ] Create migrations for new models
* [ ] Management command for importing data from shp/csv
* [ ] API routes
* [ ] Test

@batpad @szabozoltan69 @thenav56  @tovari @LukeCaley

**Comment by geohacker** [comment] 2022-09-22 04:49
<img width="929" alt="image" src="https://user-images.githubusercontent.com/371666/191658949-3a25fd4c-388e-4aa8-b37e-175da0b1d4bf.png">

The data _looks_ ok but there are problems. Overall:
1. There are 2584 points
2. It's unclear what NS_Type, NS_SubType. These have several options that looks not very clean `1,2,3,4, some lat/lng values, IFRC` etc

What attributes do we want to import?
1. Country ISO (2 or 3)
2. National Society name
3. Branch name 
4. Branch type (we don't have this now. NS/IFRC/Sub-branch?) 
5. Created timestamp
6. Last updated timestamp
7. Draft boolean (default false)
8. Validated boolean (default true)
9. Source? (NS, ICRC, Others?)
10. Sensitive / Public ?
12. Address

**Comment by esario** [comment] 2022-09-22 06:25
I have an up-to-date highly accurate dataset of Finnish RC branch data. The issue is that there's no point data, only polygons (branch polygons are comprised of 1-n zip code areas). I can compute centroids, but for attributes, there is no address and postcode data - appreciate any advice on how to tackle.

**Comment by geohacker** [comment] 2022-10-18 14:11
@esario do you mind sharing that data with me? We can handle computing centroids during the import. For address and postcode, I'd suggest we leave them empty for now and then when you have it either go through the GO Admin to edit or reimport if that's too slow a process.

**Comment by geohacker** [comment] 2022-10-18 14:11
To move forward on this, we decided in Kathmandu that we'd start with Ukraine data that looks reasonably complete.

**Comment by batpad** [comment] 2022-12-01 11:57
cc @willemarcel here - it would be great if you could start looking at this. I think what we'd need roughly:

 - [ ] A new model for `NSBranchOffice` or so that would have a ForeignKey to `Country` and the attributes listed above (@geohacker please confirm)
 - [ ] Add API endpoints to LIST Branch offices, with some filters (perhaps just `country` for now), and GET details of a branch office.
 - [ ] Ensure that Admin interface to edit Branch offices work, including ability to move point on the map.
 - [ ] Import scripts to be able to import this data via a management command from a CSV or so (@geohacker can help with this).
 - [ ] Tests to cover the above.

@willemarcel let's catch up on this when possible - @geohacker can you add any clarifications, etc. to the above?

**Comment by tovari** [comment] 2023-02-13 10:11
@willemarcel, would you mind adding the required, optional attribute naming of the import file to this ticket?

**Comment by szabozoltan69** [comment] 2023-02-15 16:03
Deployed to Staging (increased phone-nr field).

**Comment by davidmuchatiza** [comment] 2023-08-07 10:42
We have made a few changes to the Local Unit data dictionary and a few suggestions on how to deal with this dataset. For now, we are focusing on the main information table, which will form the global dataset. However, in the second version, we would explore having a unique local table for secondary information for each National Society, and this table will be primary based on the information provided by each NS during batch imports. Please see the attached files and the [link to the UI](https://www.figma.com/proto/u0XifdJwTEx165x3e0eoP9/IFRC-GO_UI-Prototype?page-id=0%3A4957&type=design&node-id=14477-242008&viewport=-1125%2C2245%2C0.11&t=OHaQxWMmgeSQ6c0H-1&scaling=scale-down-width&starting-point-node-id=0%3A4963&hide-ui=1) done by YU.
[Local Units Data Dictionary - Copy.xlsx](https://github.com/IFRCGo/go-api/files/12275214/Local.Units.Data.Dictionary.-.Copy.xlsx)

So now as the next step, tomorrow will have a discussion with DFS and YU on the work to ingest the wireframes to staging and production.

**Comment by frozenhelium** [comment] 2024-05-14 06:04
@tovari should we close this now?

**Closed** 2024-06-14 13:41 UTC
Labels: feature, geo
