### ISSUE TITLE
Update azure storage wrapper library

### ISSUE THREAD

**Issue by thenav56** [IFRCGo/go-api#1518] opened 2022-09-16 09:04 UTC
We are currently using a manual wrapper to interact with Azure through Django.
Which is outdated and not maintained.

Let's use community-developed Django storage which supports Azure storage. https://github.com/jschneier/django-storages

- #1517

**Comment by szabozoltan69** [comment] 2023-02-16 17:19
Duplicate of https://github.com/IFRCGo/go-api/issues/1678

**Closed** 2023-11-15 10:45 UTC
Labels: enhancement, Maintenance
